services:
  - type: web
    name: flask-chatbot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPEN_API_KEY
        value: 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 # Replace with your actual key
    disk:
      name: uploads
      mountPath: /var/data/uploads